version: 2
jobs:
  build:

    working_directory: ~/policy-machine-core

    docker:
      - image: cimg/openjdk:16.0.1
        
    steps:
      - checkout # check out source code to working directory
      - run: mvn dependency:go-offline # gets the project dependencies
      - run: mvn package # run the actual tests